# =============================================================================
# src/models.py
# Model architectures for the FQT (Federated Quantum-Train) framework.
# =============================================================================
# This module defines two core neural network components:
#
#   1. TargetCNN  — A classical 3-block CNN that classifies MFCCs as
#                   real or deepfake audio. Its weights are NOT trained
#                   directly; instead, they are generated by the quantum
#                   generator below (Quantum-Train paradigm).
#
#   2. QuantumTrainGenerator — A hybrid quantum-classical weight generator.
#      Architecture pipeline:
#        [MFCC input] → mfcc_to_quantum_input() → [VQC (PennyLane)]
#                     → [MLP mapping network] → [Target CNN block weights]
#
# The key insight: only the VQC parameters and MLP weights are explicitly
# trained. The TargetCNN's weights are *synthesized on the fly*, dramatically
# reducing the effective parameter count for edge-device deployment.
# =============================================================================

import torch
import torch.nn as nn
import pennylane as qml
import numpy as np

# Fix seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)


# =============================================================================
# QUANTUM CIRCUIT SETUP (PennyLane)
# =============================================================================

N_QUBITS = 17   # Matches the dimensionality of MFCC mean+std statistics
N_LAYERS = 2    # Number of BasicEntangler layers — controls expressiveness

# Initialize a PennyLane simulator device
dev = qml.device("default.qubit", wires=N_QUBITS)


@qml.qnode(dev, interface="torch", diff_method="backprop")
def qnn_circuit(inputs: torch.Tensor, weights: torch.Tensor) -> list:
    """
    Variational Quantum Circuit (VQC) for the FQT generator.

    Architecture:
        - AngleEmbedding: encodes the N_QUBITS-dimensional input vector
          as rotation angles (Ry gates) on each qubit.
        - BasicEntanglerLayers: applies N_LAYERS of parameterized Ry
          rotations followed by a ring of CNOT entanglement gates.
        - Measurement: returns the expectation value ⟨Z⟩ on each qubit,
          yielding an N_QUBITS-dimensional output vector.

    Args:
        inputs  (Tensor): Shape (N_QUBITS,). MFCC-derived quantum input.
        weights (Tensor): Shape (N_LAYERS, N_QUBITS). Trainable VQC params.

    Returns:
        list: N_QUBITS Pauli-Z expectation values in [-1, 1].
    """
    # Encode classical MFCC features as qubit rotation angles
    qml.AngleEmbedding(inputs, wires=range(N_QUBITS))
    # Apply trainable entangling layers
    qml.BasicEntanglerLayers(weights, wires=range(N_QUBITS))
    # Measure each qubit in the Z basis
    return [qml.expval(qml.PauliZ(i)) for i in range(N_QUBITS)]


def mfcc_to_quantum_input(mfcc: torch.Tensor) -> torch.Tensor:
    """
    Compress a 2D MFCC tensor into a 1D quantum input vector.

    Computes per-coefficient mean and standard deviation across the time
    axis, then concatenates them into a 2*n_mfcc vector. This is then
    clipped or zero-padded to exactly N_QUBITS dimensions so it can be
    embedded as qubit rotation angles.

    Args:
        mfcc (Tensor): Shape (n_mfcc, time) — a single MFCC matrix.

    Returns:
        Tensor: Shape (N_QUBITS,). Compressed quantum input.
    """
    mean = mfcc.mean(dim=1)    # (n_mfcc,)
    std  = mfcc.std(dim=1)     # (n_mfcc,)
    stats = torch.cat([mean, std])  # (2*n_mfcc,)

    # Resize to N_QUBITS via truncation or zero-padding
    if stats.shape[0] > N_QUBITS:
        stats = stats[:N_QUBITS]
    else:
        stats = torch.nn.functional.pad(stats, (0, N_QUBITS - stats.shape[0]))

    return stats


# =============================================================================
# MLP MAPPING NETWORK
# =============================================================================

class MLPMapping(nn.Module):
    """
    Multi-Layer Perceptron that maps quantum circuit outputs to CNN weights.

    Receives the N_QUBITS-dimensional VQC output and linearly projects it
    to a target weight vector of a specified size. A Tanh activation bounds
    the generated weights to (-1, 1), preventing gradient explosion.

    Args:
        input_dim (int):  Dimension of VQC output (= N_QUBITS).
        output_dim (int): Number of weights to generate for a CNN block.
    """

    def __init__(self, input_dim: int, output_dim: int):
        super().__init__()
        hidden_dim = max(64, output_dim // 2)  # Adaptive hidden layer size
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim),
            nn.Tanh()   # Bound generated weights to (-1, 1)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x (Tensor): VQC output, shape (N_QUBITS,) or (batch, N_QUBITS).
        Returns:
            Tensor: Generated CNN weight vector, shape (output_dim,).
        """
        return self.net(x)


# =============================================================================
# TARGET CNN (Classical Classifier)
# =============================================================================

class TargetCNN(nn.Module):
    """
    Classical CNN deepfake audio classifier operating on MFCC spectrograms.

    Architecture (3 convolutional blocks + fully-connected head):
        Block 1: Conv2d(1→16, 3×3) → BatchNorm → ReLU → MaxPool(2×2)
        Block 2: Conv2d(16→32, 3×3) → BatchNorm → ReLU → MaxPool(2×2)
        Block 3: Conv2d(32→64, 3×3) → BatchNorm → ReLU → AdaptiveAvgPool
        Head:    Flatten → Linear(64→32) → ReLU → Linear(32→2)

    Input:  Tensor of shape (batch, 1, n_mfcc, max_len)
    Output: Tensor of shape (batch, 2) — raw logits for [real, fake]

    Note:
        In the Quantum-Train paradigm, the Conv2d layer weights are
        *replaced* at inference by the output of QuantumTrainGenerator.
        The BatchNorm and FC layers retain their own learned parameters.
    """

    def __init__(self):
        super().__init__()

        # --- Block 1 ---
        self.conv1 = nn.Conv2d(1, 16, kernel_size=3, padding=1)
        self.bn1   = nn.BatchNorm2d(16)

        # --- Block 2 ---
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, padding=1)
        self.bn2   = nn.BatchNorm2d(32)

        # --- Block 3 ---
        self.conv3 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.bn3   = nn.BatchNorm2d(64)

        # Pooling layers
        self.pool       = nn.MaxPool2d(2, 2)
        self.global_pool = nn.AdaptiveAvgPool2d((1, 1))

        # Activation
        self.relu = nn.ReLU()

        # Classifier head
        self.fc1 = nn.Linear(64, 32)
        self.fc2 = nn.Linear(32, 2)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x (Tensor): MFCC input, shape (batch, 1, n_mfcc, max_len).
        Returns:
            Tensor: Logits, shape (batch, 2).
        """
        # Block 1
        x = self.pool(self.relu(self.bn1(self.conv1(x))))
        # Block 2
        x = self.pool(self.relu(self.bn2(self.conv2(x))))
        # Block 3 (global pooling → fixed-size feature vector)
        x = self.global_pool(self.relu(self.bn3(self.conv3(x))))
        # Classifier
        x = x.flatten(1)
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return x


# =============================================================================
# QUANTUM-TRAIN GENERATOR (Hybrid QNN + CNN)
# =============================================================================

class QuantumTrainGenerator(nn.Module):
    """
    Hybrid Quantum-Classical model that generates TargetCNN weights via VQC.

    The Quantum-Train paradigm works as follows:
        1. A compressed quantum input is derived from the MFCC (via
           mfcc_to_quantum_input).
        2. This input is fed into the VQC (qnn_circuit), which produces
           an N_QUBITS-dimensional measurement expectation vector.
        3. Three separate MLP mapping heads project the VQC output onto
           the weight tensors of the three CNN conv blocks.
        4. The dynamically-generated weights are injected into a forward
           pass of the TargetCNN — no separate CNN training is needed.

    During federated learning, only the VQC weights (self.quantum_weights)
    and MLP parameters (self.map1/2/3) are transmitted between clients
    and the aggregation server.

    Args:
        target_cnn (TargetCNN): The classical CNN whose conv weights to generate.
    """

    def __init__(self, target_cnn: TargetCNN):
        super().__init__()
        self.target_cnn = target_cnn

        # --- Trainable VQC parameters ---
        # Shape: (N_LAYERS, N_QUBITS) — the only quantum parameters
        self.quantum_weights = nn.Parameter(
            torch.randn(N_LAYERS, N_QUBITS) * 0.1
        )

        # --- MLP mapping heads (one per CNN conv block) ---
        # Each head generates the flattened weight tensor for a conv layer.

        # Block 1: Conv2d(1→16, 3×3) → 1×16×3×3 = 144 weights
        conv1_size = 1 * 16 * 3 * 3
        self.map1 = MLPMapping(N_QUBITS, conv1_size)

        # Block 2: Conv2d(16→32, 3×3) → 16×32×3×3 = 4608 weights
        conv2_size = 16 * 32 * 3 * 3
        self.map2 = MLPMapping(N_QUBITS, conv2_size)

        # Block 3: Conv2d(32→64, 3×3) → 32×64×3×3 = 18432 weights
        conv3_size = 32 * 64 * 3 * 3
        self.map3 = MLPMapping(N_QUBITS, conv3_size)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Full forward pass: quantum weight generation → CNN classification.

        Args:
            x (Tensor): MFCC input batch, shape (batch, 1, n_mfcc, max_len).

        Returns:
            Tensor: Classification logits, shape (batch, 2).
        """
        # Step 1: Derive quantum input from the first sample's MFCC
        # (batch-level average for efficiency; could also be per-sample)
        mfcc_sample = x[0, 0]  # Shape: (n_mfcc, max_len)
        q_input = mfcc_to_quantum_input(mfcc_sample)

        # Step 2: Run the VQC — returns list of N_QUBITS expectation values
        q_out = qnn_circuit(q_input, self.quantum_weights)
        q_out = torch.stack(q_out)  # Shape: (N_QUBITS,)

        # Step 3: Generate CNN block weights from VQC output via MLP heads
        w1 = self.map1(q_out).reshape(16, 1, 3, 3)   # conv1 weight tensor
        w2 = self.map2(q_out).reshape(32, 16, 3, 3)  # conv2 weight tensor
        w3 = self.map3(q_out).reshape(64, 32, 3, 3)  # conv3 weight tensor

        # Step 4: Inject generated weights into TargetCNN conv layers
        self.target_cnn.conv1.weight = nn.Parameter(w1)
        self.target_cnn.conv2.weight = nn.Parameter(w2)
        self.target_cnn.conv3.weight = nn.Parameter(w3)

        # Step 5: Forward pass through the TargetCNN with generated weights
        return self.target_cnn(x)
